### ISSUE TITLE
py3.6, cannot attach to remote

### ISSUE THREAD

**Issue by agroszer** [bluebird75/winpdb#16] opened 2018-12-14 15:12 UTC
```
  File "/work/proj/ve/lib/python3.6/site-packages/rpdb2.py", line 10395, in ConnectNoThrow
    self.Connect()
  File "/work/proj/ve/lib/python3.6/site-packages/rpdb2.py", line 10406, in Connect
    server_info = server.server_info()
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/work/proj/ve/lib/python3.6/site-packages/rpdb2.py", line 9673, in __request
    (fcompress, digest, msg) = self.m_crypto.do_crypto(args, fencrypt)
  File "/work/proj/ve/lib/python3.6/site-packages/rpdb2.py", line 4833, in do_crypto
    s = self.__encrypt(s)
  File "/work/proj/ve/lib/python3.6/site-packages/rpdb2.py", line 4873, in __encrypt
    d = DES.new(key_padded, DES.MODE_CBC, iv)
  File "/work/proj/ve/lib/python3.6/site-packages/Crypto/Cipher/DES.py", line 145, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/work/proj/ve/lib/python3.6/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/work/proj/ve/lib/python3.6/site-packages/Crypto/Cipher/_mode_cbc.py", line 293, in _create_cbc_cipher
    return CbcMode(cipher_state, iv)
  File "/work/proj/ve/lib/python3.6/site-packages/Crypto/Cipher/_mode_cbc.py", line 97, in __init__
    c_uint8_ptr(iv),
  File "/work/proj/ve/lib/python3.6/site-packages/Crypto/Util/_raw_api.py", line 144, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code

```

**Comment by gpatel-fr** [comment] 2019-10-05 12:53
https://github.com/bluebird75/winpdb/pull/29 was intended to fix this issue.

**Comment by bluebird75** [comment] 2019-10-11 16:23
Indeed, this is fixed in the Git version.

**Closed** 2019-10-11 16:23 UTC
