### ISSUE TITLE
Error with Python 3.3 under Linux

### ISSUE THREAD

**Issue by bluebird75** [bluebird75/winpdb#1] opened 2013-12-27 14:44 UTC
When using winpdb with Python 3.3, it fails with a ValueError on the module signal. 

chiel@ENIAC:~/Projects$ python3.3 winpdb/rpdb2.py --debug --debuggee ~/foo.py
A password should be set to secure debugger client-server communication.
Please type a password:x
Password has been set.
11:22:35.104 rpdb2.py:14178 in StartServer: Starting server with: /home/chiel/foo.py
Traceback (most recent call last):
  File "winpdb/rpdb2.py", line 14499, in <module>
    ret = rpdb2.main 
  File "/home/chiel/Projects/winpdb/rpdb2.py", line 14470, in main
    StartServer(_rpdb2_args, fchdir, _rpdb2_pwd, fAllowUnencrypted, fAllowRemote, secret)
  File "/home/chiel/Projects/winpdb/rpdb2.py", line 14212, in StartServer
    g_module_main = -1
  File "/home/chiel/Projects/winpdb/rpdb2.py", line 14212, in StartServer
    g_module_main = -1
  File "/home/chiel/Projects/winpdb/rpdb2.py", line 7324, in trace_dispatch_init
    self.__set_signal_handler()
  File "/home/chiel/Projects/winpdb/rpdb2.py", line 7286, in __set_signal_handler
    handler = signal.getsignal(value)
  File "/home/chiel/Projects/winpdb/rpdb2.py", line 13682, in __getsignal
    handler = g_signal_handlers.get(signum, g_signal_getsignal(signum))
ValueError: signal number out of range
11:22:35.198 rpdb2.py:14030 in _atexit: Entered _atexit() in pid 3422
11:22:36.199 rpdb2.py:9612 in stop: Stopping IO server... (pid = 3422)
11:22:37.979 rpdb2.py:9286 in shutdown: Shutting down worker queue...
11:22:37.980 rpdb2.py:9303 in shutdown: Shutting down worker queue, done.
11:22:37.980 rpdb2.py:9634 in stop: Stopping IO server, done.

Problem reported by  ctenbrinke on the newsgroup.

Problem does not show up on Windows with python 3.3 and does not show up on Linux with Python 3.2

**Comment by galkinvv** [comment] 2016-07-05 21:53
This issue is outdated: winpdb from this repo works fine on linux with python 3.3-3.5!

I came up with the exactly same issue with official winpdb 1.4.8 from 2010.
But in this forked repo the issue is already fixed by adding more exclusions to signal list:
https://github.com/bluebird75/winpdb/pull/2/commits/a84b1a5689584aab08f7e60caac2e6c3609f1e24

(verified on d9179bab76a6692037e5c672b6973a46fb383490 that reverting the commit above introduces exactly this issue)
So, I assume issue can be closed.

**Closed** 2017-07-02 14:08 UTC
